name: Run tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          uv run python3 -m playwright install chromium --only-shell

      - name: Run tests
        run: |
          uv run pytest
